Fix for pandas version in ARBORETO
Tentative fix for the following error when running algorithms from
ARBORETO container:

INFO:    Convert SIF file to sandbox...
Traceback (most recent call last):
  File "runArboreto.py", line 43, in <module>
    main(sys.argv)
  File "runArboreto.py", line 32, in main
    network = genie3(inDF, client_or_address = client)
  File "/opt/conda/lib/python3.7/site-packages/arboreto/algo.py", line
73, in genie3
    limit=limit, seed=seed, verbose=verbose)
  File "/opt/conda/lib/python3.7/site-packages/arboreto/algo.py", line
115, in diy
    expression_matrix, gene_names, tf_names
= _prepare_input(expression_data, gene_names, tf_names)
  File "/opt/conda/lib/python3.7/site-packages/arboreto/algo.py", line
214, in _prepare_input
    expression_matrix = expression_data.as_matrix()
  File "/opt/conda/lib/python3.7/site-packages/pandas/core/generic.py",
line 5130, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'

The actual source of the error is upstream, since the bioconda recipe does not
specify versions of the packages.